function getCalendarData(token, requestedStudentId, startDate, endDate) {
  try {
    const account=requireSession_(token), role=account.ParentID?'PARENT':String(account.Role||'STUDENT'), student=calendarStudentFor_(account,role,requestedStudentId);
    const start=parseDateOnly_(startDate)||new Date(now_().getFullYear(),now_().getMonth(),1), end=parseDateOnly_(endDate)||new Date(start.getFullYear(),start.getMonth()+1,7);
    if((end-start)/86400000>70)throw new Error('Calendar range is too large.');
    return {ok:true,data:clientSafe_({student:{id:student.StudentID,name:student.StudentName},events:calendarEvents_(student.StudentID,start,end),upcoming:upcomingEvents_(student.StudentID,8)})};
  } catch(error){return publicError_(error);}
}

function calendarStudentFor_(account,role,requestedStudentId){
  if(role==='STUDENT')return account;
  if(role!=='PARENT')throw new Error('This calendar is available to students and linked parents.');
  const links=rows_('Parent_Students').filter(l=>String(l.ParentID)===String(account.ParentID)&&String(l.Status).toLowerCase()==='active'), id=clean_(requestedStudentId,60)||String((links[0]||{}).StudentID||'');
  if(!links.some(l=>String(l.StudentID)===id))throw new Error('You are not authorized to view this student.');
  const student=findStudent_(id);if(!student)throw new Error('Linked student not found.');return student;
}

function calendarEvents_(studentId,start,end){
  const events=[], rules=rows_('ScheduleRules').filter(r=>String(r.StudentID)===String(studentId)&&String(r.Status).toLowerCase()==='active'), dayNames=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
  for(let d=new Date(start.getFullYear(),start.getMonth(),start.getDate());d<=end;d.setDate(d.getDate()+1))rules.filter(r=>String(r.DayOfWeek)===dayNames[d.getDay()]).forEach(r=>events.push({id:r.RuleID+'_'+dateKey_(d),sourceId:r.RuleID,date:dateKey_(d),type:r.Type,title:r.Title,startTime:r.StartTime||'',endTime:r.EndTime||'',mode:r.Mode||'',description:r.Description||'',status:'Upcoming',attendance:'',xp:asNumber_(r.XP),recurring:true}));
  const sessions=rows_('Learning_Sessions').filter(s=>String(s.StudentID)===String(studentId));
  sessions.forEach(s=>{const date=dateKey_(s.Date);if(date<dateKey_(start)||date>dateKey_(end))return;for(let i=events.length-1;i>=0;i--)if(events[i].date===date&&events[i].type==='SESSION')events.splice(i,1);events.push({id:s.SessionID,sourceId:s.SessionID,date:date,type:'SESSION',title:s.Title||'Offline Learning Session',startTime:s.StartTime||'',endTime:s.EndTime||endTimeFromDuration_(s.StartTime,s.Duration),mode:s.Mode||'Offline',description:s.Notes||s.TeacherNote||'',status:s.Status||'Upcoming',attendance:s.Attendance||'',xp:0,recurring:false});});
  const assignmentMap=rows_('Assignments').reduce((m,a)=>(m[a.AssignmentID]=a,m),{});
  rows_('Assignment_Submissions').filter(s=>String(s.StudentID)===String(studentId)).forEach(s=>{const a=assignmentMap[s.AssignmentID]||{}, raw=s.DueDate||a.DueDate||s.StartedAt;if(!raw)return;const date=dateKey_(raw);if(date<dateKey_(start)||date>dateKey_(end))return;events.push({id:'ASN_'+s.SubmissionID,sourceId:s.AssignmentID,date:date,type:s.DueDate||a.DueDate?'DEADLINE':'ASSIGNMENT',title:a.Title||'Practical Assignment',startTime:'',endTime:'',mode:'Online',description:a.ShortDescription||'',status:s.Status||'Assigned',attendance:'',xp:asNumber_(a.XP),recurring:false});});
  return events.sort((a,b)=>a.date.localeCompare(b.date)||String(a.startTime).localeCompare(String(b.startTime)));
}
function upcomingEvents_(studentId,limit){const start=new Date(),end=new Date();end.setDate(end.getDate()+35);return calendarEvents_(studentId,start,end).filter(e=>!['Cancelled','Completed'].includes(e.status)&&new Date(e.date+'T23:59:59')>=start).slice(0,limit||6);}
function parseDateOnly_(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value||'')))return null;const d=new Date(String(value)+'T00:00:00');return Number.isNaN(d.getTime())?null:d;}
function endTimeFromDuration_(start,duration){const match=String(duration||'').match(/(\d+)/);if(!start||!match)return'';const parts=String(start).split(':'),d=new Date(2000,0,1,Number(parts[0]),Number(parts[1]||0)+Number(match[1]));return Utilities.formatDate(d,CONFIG.TIMEZONE,'HH:mm');}

function getNotifications(token){try{const user=requireSession_(token),id=user.ParentID||user.StudentID;return {ok:true,data:clientSafe_(rows_('Notifications').filter(n=>String(n.UserID)===String(id)).slice(-50).reverse().map(stripRow_))};}catch(error){return publicError_(error);}}
function markNotificationRead(token,notificationId,all){try{const user=requireSession_(token),id=String(user.ParentID||user.StudentID);rows_('Notifications').filter(n=>String(n.UserID)===id&&(all||String(n.NotificationID)===clean_(notificationId,60))).forEach(n=>updateRow_('Notifications',n._row,{IsRead:true}));return {ok:true};}catch(error){return publicError_(error);}}
function createNotification_(userId,studentId,type,title,message,entity,eventKey){if(rows_('Notifications').some(n=>String(n.UserID)===String(userId)&&String(n.EventKey)===String(eventKey)))return;append_('Notifications',{NotificationID:id_('NOT'),UserID:userId,StudentID:studentId,Type:type,Title:title,Message:message,RelatedEntityID:entity||'',IsRead:false,CreatedAt:now_(),EventKey:eventKey});}

function getNotificationPreferences(token){try{const p=requireSession_(token,'PARENT'),row=rows_('NotificationPreferences').find(x=>String(x.ParentID)===String(p.ParentID));return {ok:true,data:preferenceView_(p.ParentID,row)};}catch(error){return publicError_(error);}}
function saveNotificationPreferences(token,form){try{const p=requireSession_(token,'PARENT'),values={MasterEnabled:bool_(form.master),QuizMilestones:bool_(form.quiz),AssignmentUpdates:bool_(form.assignment),Achievements:bool_(form.achievements),SessionUpdates:bool_(form.sessions),WeeklyProgress:bool_(form.weekly),UpdatedAt:now_()},row=rows_('NotificationPreferences').find(x=>String(x.ParentID)===String(p.ParentID));if(row)updateRow_('NotificationPreferences',row._row,values);else append_('NotificationPreferences',Object.assign({ParentID:p.ParentID},values));return {ok:true,data:preferenceView_(p.ParentID,Object.assign({ParentID:p.ParentID},values))};}catch(error){return publicError_(error);}}
function preferenceView_(parentId,row){return {parentId:parentId,master:row?bool_(row.MasterEnabled):true,quiz:row?bool_(row.QuizMilestones):true,assignment:row?bool_(row.AssignmentUpdates):true,achievements:row?bool_(row.Achievements):true,sessions:row?bool_(row.SessionUpdates):true,weekly:row?bool_(row.WeeklyProgress):true};}
function bool_(value){return value===true||String(value).toLowerCase()==='true'||String(value).toLowerCase()==='on';}

function safeLearningEvent_(studentId,type,data){try{processLearningEvent_(studentId,type,data||{});}catch(error){console.error('Learning communication failed',error);}}
function processLearningEvent_(studentId,type,data){const student=findStudent_(studentId);if(!student)return;if(type==='QUESTION'){processQuizMilestone_(student,data.topic);if(asNumber_(student.Level)>1)sendProgressEvent_(student,'LEVEL_INCREASED','LEVEL_'+student.Level,'Level '+student.Level+' reached',student.StudentName+' advanced to Level '+student.Level+'.',{level:student.Level});}if(type==='ASSIGNMENT_COMPLETED')sendProgressEvent_(student,'ASSIGNMENT_COMPLETED',data.assignmentId,data.title+' completed',data.title+' was reviewed and marked completed.',data);if(type==='ASSIGNMENT_ASSIGNED')sendProgressEvent_(student,'NEW_ASSIGNMENT',data.assignmentId,'New assignment: '+data.title,data.title+' is ready to begin.',data);if(type==='TEACHER_FEEDBACK')sendProgressEvent_(student,'TEACHER_FEEDBACK',data.assignmentId+'_'+data.status,'New teacher feedback',data.message||'Teacher feedback is available.',data);if(type==='SESSION_UPDATE')sendProgressEvent_(student,'SESSION_'+String(data.status||'UPDATED').toUpperCase(),data.sessionId+'_'+data.status,data.title||'Session update',(data.title||'Learning session')+' is '+String(data.status||'updated').toLowerCase()+'.',data);(data.badges||[]).forEach(b=>sendProgressEvent_(student,'BADGE_EARNED',b.id,'Badge earned: '+b.name,b.description||'A new badge was unlocked.',{badge:b}));}
function processQuizMilestone_(student,topic){const questionIds=new Set(rows_('Questions').filter(q=>String(q.Topic).toLowerCase()===String(topic).toLowerCase()).map(q=>String(q.QuestionID))),completed=rows_('Progress').filter(p=>String(p.StudentID)===String(student.StudentID)&&p.Status==='Completed'&&questionIds.has(String(p.QuestionID))).length;if(!completed||completed%10!==0)return;sendProgressEvent_(student,'QUIZ_MILESTONE',String(topic)+'_'+completed,topic+' quiz milestone',student.StudentName+' completed '+completed+' '+topic+' questions.',{topic:topic,milestone:completed});}
function sendProgressEvent_(student,eventType,entity,title,message,data){const eventKey=[student.StudentID,eventType,entity].join('_');createNotification_(student.StudentID,student.StudentID,eventType,title,message,entity,eventKey);const links=rows_('Parent_Students').filter(l=>String(l.StudentID)===String(student.StudentID)&&String(l.Status).toLowerCase()==='active');links.forEach(l=>createNotification_(l.ParentID,student.StudentID,eventType,title,message,entity,eventKey));const recipients=progressRecipients_(student.StudentID,links,eventType);recipients.forEach(r=>sendProgressEmail_(student,eventType,eventKey,r,data||{}));}
function progressRecipients_(studentId,links,eventType){
  const result=[],type=String(eventType);
  links.forEach(l=>{
    const p=findParent_(l.ParentID),prefRow=rows_('NotificationPreferences').find(x=>String(x.ParentID)===String(l.ParentID)),pref=preferenceView_(l.ParentID,prefRow);
    const categoryAllowed=type==='QUIZ_MILESTONE'?pref.quiz:(type.indexOf('ASSIGNMENT')>=0||type==='NEW_ASSIGNMENT'||type==='TEACHER_FEEDBACK')?pref.assignment:type==='BADGE_EARNED'||type==='LEVEL_INCREASED'?pref.achievements:type.indexOf('SESSION_')===0?pref.sessions:type==='WEEKLY_REPORT'?pref.weekly:true;
    if(p&&p.Email&&pref.master&&categoryAllowed)result.push({email:String(p.Email),name:p.ParentName,parentId:p.ParentID});
  });
  rows_('NotificationRecipients').filter(r=>String(r.StudentID)===String(studentId)&&bool_(r.Enabled)&&r.RecipientEmail).forEach(r=>result.push({email:String(r.RecipientEmail),name:r.RecipientName||r.RecipientType,parentId:r.ParentID||''}));
  return result.filter((r,i,a)=>a.findIndex(x=>x.email.toLowerCase()===r.email.toLowerCase())===i);
}
function sendProgressEmail_(student,eventType,eventKey,recipient,data){
  const unique=eventKey+'_'+recipient.email.toLowerCase();if(rows_('EmailLog').some(x=>String(x.EventKey)===unique&&String(x.Status)==='Sent'))return;
  const subject=emailSubject_(student,eventType,data),logId=id_('EML');append_('EmailLog',{NotificationID:logId,StudentID:student.StudentID,EventType:eventType,Topic:data.topic||'',Milestone:data.milestone||'',RecipientEmail:recipient.email,Subject:subject,Status:'Pending',EventKey:unique});const log=rows_('EmailLog').find(x=>x.NotificationID===logId);
  try{MailApp.sendEmail({to:recipient.email,subject:subject,htmlBody:progressEmailHtml_(student,eventType,data),name:'OPSNORA Learn'});updateRow_('EmailLog',log._row,{Status:'Sent',SentAt:now_(),ErrorMessage:''});}catch(error){updateRow_('EmailLog',log._row,{Status:'Failed',ErrorMessage:clean_(error.message,500)});}
}
function emailSubject_(student,eventType,data){if(eventType==='QUIZ_MILESTONE')return student.StudentName+' completed '+data.milestone+' '+data.topic+' questions 🎉 | OPSNORA Learn';if(eventType==='ASSIGNMENT_COMPLETED')return student.StudentName+' completed '+data.title+' | OPSNORA Learn';if(String(eventType).indexOf('SESSION_')===0)return 'Session update for '+student.StudentName+' | OPSNORA Learn';if(eventType==='WEEKLY_REPORT')return student.StudentName+'\'s weekly progress | OPSNORA Learn';return 'New achievement for '+student.StudentName+' | OPSNORA Learn';}
function progressEmailHtml_(student,eventType,data){
  const dash=studentDashboard_(student),s=dash.stats,title=eventType==='QUIZ_MILESTONE'?data.topic+' QUIZ MILESTONE':eventType==='ASSIGNMENT_COMPLETED'?'ASSIGNMENT COMPLETED':eventType==='WEEKLY_REPORT'?'WEEKLY PROGRESS REPORT':String(eventType).indexOf('SESSION_')===0?'SESSION UPDATE':'ACHIEVEMENT UNLOCKED',focus=eventType==='QUIZ_MILESTONE'?data.milestone+' Questions Completed':eventType==='ASSIGNMENT_COMPLETED'?data.title:(data.badge||{}).name||title;
  let detail='';
  if(eventType==='ASSIGNMENT_COMPLETED'){
    detail='<p style="color:#aab4cf"><b>Status:</b> Completed'+(data.xp?' &nbsp; <b>XP earned:</b> +'+Number(data.xp):'')+'</p>';
    if(data.teacherRemarks)detail+='<p style="background:#0a0f1e;padding:12px;color:#cbd4e9"><b>Teacher feedback:</b><br>'+escapeHtml_(data.teacherRemarks)+'</p>';
  }else if(eventType==='QUIZ_MILESTONE'){
    detail='<p style="color:#aab4cf;text-align:center">'+escapeHtml_(data.topic)+' &middot; '+Number(data.milestone)+' completed questions</p>';
  }
  return '<div style="background:#070914;padding:24px;font-family:Arial,sans-serif;color:#f7f8ff"><table role="presentation" width="100%" style="max-width:640px;margin:auto;background:#10162a;border:1px solid #293451;border-radius:18px"><tr><td style="padding:28px"><div style="color:#56c5ff;font-weight:bold">OPSNORA LEARN</div><p style="color:#8f9aba;font-size:12px">LEARNING PROGRESS UPDATE</p><h2 style="margin:20px 0 4px">'+escapeHtml_(student.StudentName)+'</h2><p style="color:#aab4cf">'+escapeHtml_(student.Class)+'</p><div style="background:#181536;border-radius:14px;padding:20px;text-align:center"><div style="color:#a990ff;font-size:12px">'+escapeHtml_(title)+'</div><h1 style="margin:10px 0">'+escapeHtml_(focus)+'</h1></div>'+detail+'<table role="presentation" width="100%" style="margin-top:18px"><tr><td style="padding:10px;background:#0a0f1e">Level<br><b>'+dash.profile.level+'</b></td><td style="padding:10px;background:#0a0f1e">Total XP<br><b>'+s.xp+'</b></td><td style="padding:10px;background:#0a0f1e">Accuracy<br><b>'+s.accuracy+'%</b></td><td style="padding:10px;background:#0a0f1e">Streak<br><b>'+s.streak+' days</b></td></tr></table><div style="margin-top:18px;background:#252d46;border-radius:8px;height:8px"><div style="width:'+Math.max(0,Math.min(100,dash.level.percent))+'%;height:8px;border-radius:8px;background:#6f55e7"></div></div><p style="color:#aab4cf;line-height:1.6">Great progress! Keep encouraging '+escapeHtml_(student.StudentName)+' to maintain the learning streak.</p><p style="color:#7884a5">Regards,<br>OPSNORA Learn</p></td></tr></table></div>';
}
function escapeHtml_(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}

function setupAutomationTriggers(){const exists=ScriptApp.getProjectTriggers().some(t=>t.getHandlerFunction()==='runScheduledAutomation');if(!exists)ScriptApp.newTrigger('runScheduledAutomation').timeBased().everyHours(6).create();return exists?'Automation trigger already exists.':'Automation trigger created.';}
function runScheduledAutomation(){try{generateSessionReminders_();generateDeadlineReminders_();generateWeeklyReports_();retryFailedEmails_();}catch(error){console.error(error);}}
function generateSessionReminders_(){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);const date=dateKey_(tomorrow);rows_('Students').filter(s=>String(s.Role||'STUDENT')==='STUDENT').forEach(student=>calendarEvents_(student.StudentID,tomorrow,tomorrow).filter(e=>e.type==='SESSION'&&e.status!=='Cancelled').forEach(e=>sendProgressEvent_(student,'SESSION_REMINDER',e.id,'Session reminder','Offline session tomorrow'+(e.startTime?' at '+e.startTime:'')+'.',{session:e})));}
function generateDeadlineReminders_(){const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);rows_('Students').filter(s=>String(s.Role||'STUDENT')==='STUDENT').forEach(student=>calendarEvents_(student.StudentID,tomorrow,tomorrow).filter(e=>e.type==='DEADLINE').forEach(e=>sendProgressEvent_(student,'ASSIGNMENT_DEADLINE',e.id,'Assignment deadline approaching',e.title+' is due tomorrow.',{assignment:e})));}
function generateWeeklyReports_(){if(Number(Utilities.formatDate(now_(),CONFIG.TIMEZONE,'u'))!==7)return;const week=Utilities.formatDate(now_(),CONFIG.TIMEZONE,"YYYY-'W'ww");rows_('Students').filter(s=>String(s.Role||'STUDENT')==='STUDENT').forEach(student=>sendProgressEvent_(student,'WEEKLY_REPORT',week,'Weekly progress report',student.StudentName+'\'s weekly learning summary is ready.',{week:week}));}
function retryFailedEmails_(){rows_('EmailLog').filter(x=>String(x.Status)==='Failed'&&x.RecipientEmail).slice(0,20).forEach(log=>{const student=findStudent_(log.StudentID);if(!student)return;try{MailApp.sendEmail({to:String(log.RecipientEmail),subject:String(log.Subject),htmlBody:progressEmailHtml_(student,String(log.EventType),{topic:log.Topic,milestone:log.Milestone}),name:'OPSNORA Learn'});updateRow_('EmailLog',log._row,{Status:'Sent',SentAt:now_(),ErrorMessage:''});}catch(error){updateRow_('EmailLog',log._row,{ErrorMessage:clean_(error.message,500)});}});}
