function getStudentDashboard(token) {
  try { const user=requireSession_(token,'STUDENT'); return {ok:true,data:clientSafe_(studentDashboard_(user))}; } catch(e){ return publicError_(e); }
}
function studentDashboard_(user) {
  user=findStudent_(user.StudentID); const attempts=rows_('Attempts').filter(x=>x.StudentID===user.StudentID), progress=rows_('Progress').filter(x=>x.StudentID===user.StudentID&&x.Status==='Completed');
  const active=activeQuestions_(), topic={};
  attempts.forEach(a=>{ if(!topic[a.Topic]) topic[a.Topic]={attempted:0,correct:0}; topic[a.Topic].attempted++; if(a.IsCorrect===true||String(a.IsCorrect).toLowerCase()==='true') topic[a.Topic].correct++; });
  const lvl=levelForXp_(asNumber_(user.TotalXP)), next=CONFIG.LEVELS.find(x=>x.level===lvl.level+1), xp=asNumber_(user.TotalXP), recentXp=rows_('XP_Log').filter(x=>x.StudentID===user.StudentID).slice(-8).reverse();
  return {profile:{id:user.StudentID,name:user.StudentName,className:user.Class,level:asNumber_(user.Level,1)},stats:{xp:xp,completed:progress.length,totalQuestions:active.length,attempted:attempts.length,correct:attempts.filter(x=>x.IsCorrect===true||String(x.IsCorrect).toLowerCase()==='true').length,wrong:attempts.filter(x=>!(x.IsCorrect===true||String(x.IsCorrect).toLowerCase()==='true')).length,accuracy:attempts.length?Math.round(attempts.filter(x=>x.IsCorrect===true||String(x.IsCorrect).toLowerCase()==='true').length/attempts.length*100):0,streak:asNumber_(user.CurrentStreak),longestStreak:asNumber_(user.LongestStreak)},level:{current:lvl.level,start:lvl.min,nextAt:next?next.min:null,toNext:next?Math.max(0,next.min-xp):0,percent:next?Math.max(0,Math.min(100,(xp-lvl.min)/(next.min-lvl.min)*100)):100},nextQuestion:nextQuestion_(user),assignments:assignmentSummary_(user.StudentID),badges:badgeView_(user),topics:Object.keys(topic).sort().map(k=>({topic:k,attempted:topic[k].attempted,accuracy:Math.round(topic[k].correct/topic[k].attempted*100)})),recent:recentXp.map(x=>({type:x.Source,title:x.Description,xp:asNumber_(x.XPChange),date:x.Timestamp}))};
}
