export function createCalendar({api,ui,esc,fmtDate,$}){
  const state={date:new Date(),view:'month',studentId:''};
  const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const monthRange=()=>({start:new Date(state.date.getFullYear(),state.date.getMonth(),1),end:new Date(state.date.getFullYear(),state.date.getMonth()+1,0)});
  const weekRange=()=>{const start=new Date(state.date);start.setDate(start.getDate()-start.getDay());const end=new Date(start);end.setDate(end.getDate()+6);return {start,end}};
  async function open(studentId='',view){state.studentId=studentId||state.studentId;state.view=view||state.view;ui.loading();const range=state.view==='week'?weekRange():monthRange(),data=(await api.calendarData(state.studentId,iso(range.start),iso(range.end))).data;render(data,range);ui.loading(false)}
  function render(data,range){const days=[],cursor=new Date(range.start);if(state.view==='month')cursor.setDate(cursor.getDate()-cursor.getDay());const finish=new Date(range.end);if(state.view==='month')finish.setDate(finish.getDate()+(6-finish.getDay()));for(let d=new Date(cursor);d<=finish;d.setDate(d.getDate()+1))days.push(new Date(d));const byDate=data.events.reduce((m,e)=>(m[e.date]??=[],m[e.date].push(e),m),{});$('#headerKicker').textContent='LEARNING SCHEDULE';$('#pageTitle').textContent='Calendar';$('#pageSubtitle').textContent=`${data.student.name}'s sessions, quizzes and assignments.`;$('#screen').innerHTML=`<div class="calendar-toolbar"><div><button class="secondary" data-calendar-nav="prev">←</button><button class="secondary" data-calendar-today>Today</button><button class="secondary" data-calendar-nav="next">→</button></div><h3>${state.view==='month'?state.date.toLocaleDateString('en-IN',{month:'long',year:'numeric'}):`${fmtDate(range.start)} – ${fmtDate(range.end)}`}</h3><div class="filter-chips"><button data-calendar-view="month" class="${state.view==='month'?'active':''}">Month</button><button data-calendar-view="week" class="${state.view==='week'?'active':''}">Week</button></div></div><div class="calendar-weekdays">${['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=>`<span>${x}</span>`).join('')}</div><div class="calendar-grid ${state.view}">${days.map(d=>{const key=iso(d),events=byDate[key]||[],outside=state.view==='month'&&d.getMonth()!==state.date.getMonth(),today=key===iso(new Date());return `<section class="calendar-day ${outside?'outside':''} ${today?'today':''}"><header><b>${d.getDate()}</b><span>${d.toLocaleDateString('en-IN',{weekday:'short'})}</span></header><div>${events.map(e=>`<button class="calendar-event type-${String(e.type).toLowerCase()}" data-calendar-event="${esc(e.id)}"><b>${esc(e.title)}</b><small>${e.startTime?esc(e.startTime):esc(e.type)}</small></button>`).join('')}</div></section>`}).join('')}</div><section class="card calendar-upcoming"><div class="card-head"><div><h3>Upcoming Activities</h3><small>Your next scheduled learning moments</small></div></div>${comingUp(data.upcoming)}</section>`;window.__opsnoraCalendarEvents=[...data.events,...data.upcoming]}
  function comingUp(items){return items?.length?`<div class="coming-up-list">${items.map(e=>`<button data-calendar-event="${esc(e.id)}"><span class="event-dot type-${String(e.type).toLowerCase()}"></span><div><b>${esc(e.title)}</b><small>${fmtDate(e.date)}${e.startTime?' · '+esc(e.startTime):''}</small></div><em>${esc(e.type)}</em></button>`).join('')}</div>`:'<div class="parent-empty">No upcoming activities.</div>'}
  function detail(id){const e=(window.__opsnoraCalendarEvents||[]).find(x=>String(x.id)===String(id));if(!e)return;let modal=$('#calendarModal');if(!modal){document.body.insertAdjacentHTML('beforeend','<div id="calendarModal" class="modal hidden"><div class="modal-card calendar-detail"><button class="calendar-close" aria-label="Close">×</button><div id="calendarDetailBody"></div></div></div>');modal=$('#calendarModal')}$('#calendarDetailBody').innerHTML=`<p class="eyebrow">${esc(e.type)}</p><h2>${esc(e.title)}</h2><div class="calendar-detail-grid"><div><span>Date</span><b>${fmtDate(e.date)}</b></div><div><span>Time</span><b>${e.startTime?esc(e.startTime)+(e.endTime?' – '+esc(e.endTime):''):'—'}</b></div><div><span>Activity Type</span><b>${esc(e.type)}</b></div><div><span>Status</span><b>${esc(e.status||'Upcoming')}</b></div>${e.mode?`<div><span>Mode</span><b>${esc(e.mode)}</b></div>`:''}${e.attendance?`<div><span>Attendance</span><b>${esc(e.attendance)}</b></div>`:''}${e.xp?`<div><span>XP available</span><b>${e.xp} XP</b></div>`:''}</div>${e.description?`<p>${esc(e.description)}</p>`:''}`;modal.classList.remove('hidden')}
  function shift(direction){if(state.view==='month')state.date.setMonth(state.date.getMonth()+direction);else state.date.setDate(state.date.getDate()+direction*7);return open()}
  return {open,comingUp,detail,shift,state,today(){state.date=new Date();return open()},setView(view){state.view=view;return open()}};
}
