import './styles.css';
import {api,session,ApiError} from './api.js';

const state={user:session.get(),data:null,catalog:null,question:null,selected:null,started:0,practiceTopic:'',quizRun:null,lastResult:null,assignment:null,assignmentDirty:false,autosaveTimer:null,adminCoding:null,review:null};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const fmtDate=value=>value?new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';

const ui={
  toast(message,type='info'){const el=$('#toast');el.textContent=message;el.className=`toast show ${type}`;clearTimeout(ui.toastTimer);ui.toastTimer=setTimeout(()=>el.className='toast',3200)},
  loading(show=true){$('#loading').classList.toggle('hidden',!show);if(show)$('#screen').innerHTML=''},
  title(kicker,title){$('#headerKicker').textContent=kicker;$('#pageTitle').textContent=title},
  badges(items){if(!items?.length)return;const badge=items[0];$('#modalIcon').textContent=badge.icon||'🏆';$('#modalTitle').textContent=badge.name;$('#modalText').textContent=badge.description;$('#modal').classList.remove('hidden')},
  closeModal(){$('#modal').classList.add('hidden')},
  async run(work){try{return await work()}catch(error){if(error instanceof ApiError&&error.code==='SESSION_EXPIRED'){auth.clear('Your session expired. Please sign in again.');return null}ui.toast(error.message||'Something went wrong.','error');return null}}
};

const auth={
  async login(event){event.preventDefault();const button=$('#loginButton');$('#loginError').textContent='';button.disabled=true;button.querySelector('span').textContent='SIGNING IN…';try{const result=await api.login($('#loginId').value.trim(),$('#loginPin').value);state.user={token:result.token,role:result.role,name:result.name};session.set(state.user);auth.showApp();await router.go(result.role==='ADMIN'?'admin':'dashboard')}catch(error){$('#loginError').textContent=error.message||'Unable to sign in.'}finally{button.disabled=false;button.querySelector('span').textContent='ENTER LEARNING SPACE'}},
  showApp(){const user=state.user;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#profileName').textContent=user?.name||'Learner';$('#avatar').textContent=(user?.name||'L')[0].toUpperCase();$('#profileClass').textContent=user?.role==='ADMIN'?'Administrator':'Class 8';document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',user?.role!=='ADMIN'));document.querySelectorAll('#nav button:not(.admin-only)').forEach(el=>el.classList.toggle('hidden',user?.role==='ADMIN'&&el.dataset.view!=='dashboard'))},
  async logout(){try{await api.logout()}catch(_){}auth.clear()},
  clear(message=''){session.clear();state.user=null;state.data=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginPin').value='';if(message)$('#loginError').textContent=message}
};

const router={
  async go(view){if(view!=='coding'&&state.assignmentDirty)await coding.save(true);if(state.user?.role==='ADMIN')view='admin';document.querySelectorAll('#nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===view));ui.loading();const page=view==='practice'?practice.catalog:view==='quizzes'?quizSets.catalog:view==='coding'?coding.home:view==='badges'?student.badges:view==='progress'?student.progress:view==='admin'?admin.home:student.home;const result=await ui.run(()=>page());if(result===null)ui.loading(false)}
};

const student={
  async fetch(force=false){if(state.data&&!force)return state.data;const result=await api.studentDashboard();state.data=result.data;student.syncHeader(result.data);return result.data},
  syncHeader(data){$('#profileName').textContent=data.profile.name;$('#profileClass').textContent=data.profile.className;$('#avatar').textContent=data.profile.name[0];$('#headerLevel').textContent=data.profile.level;$('#headerXp').textContent=data.stats.xp},
  stat(icon,value,label){return `<article class="card stat"><span class="icon">${icon}</span><strong>${value}</strong><small>${label}</small></article>`},
  badgeHtml(badges){return badges.map(b=>`<div class="badge ${b.earned?'':'locked'}" title="${esc(b.description)}"><div class="medal">${esc(b.icon||'✦')}</div><small>${esc(b.name)}</small></div>`).join('')||'<p class="muted">No badges available yet.</p>'},
  activity(items){return `<div class="activity">${items.map(item=>`<div class="activity-item"><span class="dot">+</span><p>${esc(item.title)}<small>${esc(item.type)} · ${fmtDate(item.date)}</small></p><b>${item.xp>=0?'+':''}${item.xp} XP</b></div>`).join('')||'<p class="muted">Your learning activity will appear here.</p>'}</div>`},
  topics(items){return items.map(item=>`<div class="topic"><div><b>${esc(item.topic)}</b><span>${item.accuracy}% · ${item.attempted} attempts</span></div><div class="bar"><i style="width:${item.accuracy}%"></i></div></div>`).join('')||'<p class="muted">Complete a quiz to unlock topic insights.</p>'},
  async home(){ui.title('STUDENT DASHBOARD','Your learning space');const data=await student.fetch(),stats=data.stats,next=data.nextQuestion;$('#screen').innerHTML=`<div class="hero"><section class="hero-main"><p class="eyebrow">WELCOME BACK</p><h1>Hey, ${esc(data.profile.name.split(' ')[0])}!<br><span class="gradient">Keep the momentum.</span></h1><p>${next?`Your next challenge is ready in ${esc(next.topic)}. Practice a topic or take a focused quiz.`:'You completed every active question. Brilliant work!'}</p><button class="primary continue" data-action="practice">START PRACTICE &nbsp; →</button></section><section class="card level-card"><div class="level-top"><div class="level-number"><small>CURRENT LEVEL</small>${data.profile.level}</div><span class="level-orb">✦</span></div><div class="bar"><i style="width:${data.level.percent}%"></i></div><div class="barline"><span>${stats.xp} XP</span><span>${data.level.nextAt?data.level.nextAt+' XP':'MAX LEVEL'}</span></div><p>${data.level.nextAt?`<b>${data.level.toNext} XP</b> to reach Level ${data.profile.level+1}`:'You reached the highest level.'}</p></section></div><div class="stats">${student.stat('⚡',stats.xp,'Total XP')}${student.stat('◇',stats.completed+' / '+stats.totalQuestions,'Questions completed')}${student.stat('◎',stats.accuracy+'%','Overall accuracy')}${student.stat('🔥',stats.streak+' days','Current streak')}</div><div class="grid2"><section class="card"><div class="card-head"><div><h3>My badges</h3><small>${data.badges.filter(x=>x.earned).length} achievements unlocked</small></div><button class="link-btn" data-action="badges">View all →</button></div><div class="badge-row">${student.badgeHtml(data.badges.slice(0,6))}</div></section><section class="card"><div class="card-head"><h3>Recent activity</h3></div>${student.activity(data.recent.slice(0,4))}</section></div><div class="grid2"><section class="card"><div class="card-head"><div><h3>Topic performance</h3><small>Accuracy across your learning areas</small></div><button class="link-btn" data-action="progress">Details →</button></div>${student.topics(data.topics.slice(0,4))}</section><section class="card"><div class="card-head"><h3>Choose your mode</h3></div><p class="muted">Prepare freely in Practice, or test yourself with 10-question quiz sets.</p><div class="result-actions" style="justify-content:flex-start"><button class="secondary" data-action="practice">Practice</button><button class="primary" data-action="quizzes">Quizzes</button></div></section></div>`;ui.loading(false)},
  async badges(){ui.title('ACHIEVEMENTS','Your badge collection');const data=await student.fetch(),earned=data.badges.filter(x=>x.earned).length;$('#screen').innerHTML=`<section class="card"><div class="card-head"><div><h3>${earned} of ${data.badges.length} unlocked</h3><small>Progress comes directly from your learning history.</small></div></div><div class="badge-grid">${data.badges.map(b=>`<article class="badge-detail ${b.earned?'':'locked'}"><div class="medal">${esc(b.icon||'✦')}</div><div class="badge-copy"><h4>${esc(b.name)}</h4><p>${esc(b.requirement||b.description)}</p>${b.earned?`<small>Unlocked · ${fmtDate(b.earnedDate)}</small>`:`<small>Progress: ${b.current} / ${b.target} ${esc(b.unit)}</small><div class="bar"><i style="width:${b.percent}%"></i></div>`}</div></article>`).join('')}</div></section>`;ui.loading(false)},
  async progress(){ui.title('PERFORMANCE','Progress & insights');const data=await student.fetch(),stats=data.stats;$('#screen').innerHTML=`<div class="stats">${student.stat('◎',stats.accuracy+'%','Overall accuracy')}${student.stat('◇',stats.attempted,'Total attempts')}${student.stat('✓',stats.correct,'Correct answers')}${student.stat('×',stats.wrong,'Incorrect answers')}</div><div class="grid2"><section class="card"><div class="card-head"><div><h3>Topic performance</h3><small>Spot strengths and areas to revisit</small></div></div>${student.topics(data.topics)}</section><section class="card"><div class="card-head"><h3>Learning streak</h3></div><div class="level-number"><small>LONGEST STREAK</small>${stats.longestStreak} <span style="font-size:18px">days 🔥</span></div><p class="muted">Current streak: ${stats.streak} days</p></section></div>`;ui.loading(false)}
};

const practice={
  async catalog(){ui.title('PRACTICE','Choose what you want to prepare');const result=state.catalog?{data:state.catalog}:await api.learningCatalog();state.catalog=result.data;$('#screen').innerHTML=`<div class="catalog-grid">${result.data.topics.map((topic,index)=>`<article class="card subject-card" data-practice-topic="${esc(topic.name)}"><div class="subject-icon">${['⌘','◈','▦','◉'][index%4]}</div><h3>${esc(topic.name)}</h3><p>${esc(topic.name)} MCQ Practice</p><div class="bar"><i style="width:${topic.total?Math.round(topic.completed/topic.total*100):0}%"></i></div><div class="subject-meta"><span>${topic.completed} completed</span><span>${topic.total} questions</span></div></article>`).join('')}</div>`;ui.loading(false)},
  async load(topic){state.practiceTopic=topic||state.practiceTopic;ui.title('PRACTICE',state.practiceTopic+' practice');state.selected=null;state.started=Date.now();const result=await api.practiceQuestion(state.practiceTopic);state.question=result.question;practice.render()},
  render(){const q=state.question;if(!q){$('#screen').innerHTML='<div class="card empty"><div class="big">🏆</div><h2>Topic complete!</h2><p>You completed every active question in this topic.</p><button class="primary" data-action="practice">BACK TO TOPICS</button></div>';ui.loading(false);return}$('#screen').innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><span>PRACTICE · QUESTION ${q.number} OF ${q.total}</span><span>${q.xp} XP AVAILABLE</span></div><div class="bar"><i style="width:${Math.round((q.number-1)/q.total*100)}%"></i></div><section class="card question-card"><div class="chips"><span class="chip">${esc(q.topic)}</span><span class="chip">${esc(q.difficulty)}</span>${q.subTopic?`<span class="chip">${esc(q.subTopic)}</span>`:''}</div><h1>${esc(q.text)}</h1><div class="options">${Object.entries(q.options).map(([key,value])=>`<button class="option" data-option="${key}"><b>${key}</b><span>${esc(value)}</span></button>`).join('')}</div><div id="feedback"></div><div class="quiz-actions"><button class="secondary" data-action="practice">EXIT PRACTICE</button><button id="practiceSubmit" class="primary" disabled>SUBMIT ANSWER</button></div></section></div>`;ui.loading(false)},
  select(key){if($('#feedback')?.innerHTML)return;state.selected=key;document.querySelectorAll('.option').forEach(el=>el.classList.toggle('selected',el.dataset.option===key));$('#practiceSubmit').disabled=false},
  async submit(){if(!state.selected)return;const button=$('#practiceSubmit');button.disabled=true;button.textContent='CHECKING…';const result=await ui.run(()=>api.submitAnswer(state.question.id,state.selected,Math.round((Date.now()-state.started)/1000)));if(!result){button.disabled=false;button.textContent='SUBMIT ANSWER';return}document.querySelectorAll('.option').forEach(el=>{el.disabled=true;if(el.dataset.option===result.correctAnswer)el.classList.add('correct');if(el.dataset.option===state.selected&&!result.correct)el.classList.add('wrong')});$('#feedback').className=`feedback${result.correct?'':' wrong'}`;$('#feedback').innerHTML=`<h3>${result.correct?`Correct! ${result.xpEarned?`+${result.xpEarned} XP`:''}`:'Not quite.'}</h3><p>${esc(result.explanation)}</p>${!result.correct?`<small>Correct answer: ${esc(result.correctAnswer)}. ${esc(result.correctText||'')}</small>`:''}`;button.textContent='NEXT QUESTION →';button.disabled=false;button.dataset.next='true';state.data=null;state.catalog=null;ui.badges(result.badges)}
};

const quizSets={
  async catalog(force=false){ui.title('QUIZZES','Test your skills in focused sets');if(force)state.catalog=null;const result=state.catalog?{data:state.catalog}:await api.learningCatalog();state.catalog=result.data;$('#screen').innerHTML=result.data.topics.map(topic=>`<section class="quiz-section"><h3 class="quiz-section-title">${esc(topic.name)}</h3><div class="catalog-grid">${topic.quizzes.map(q=>`<article class="card quiz-card" data-quiz-topic="${esc(topic.name)}" data-quiz-number="${q.number}"><div class="subject-icon">▤</div><h3>${esc(q.name)}</h3><p>Questions ${esc(q.range)} · ${q.count} total</p><span class="quiz-status">${q.attempted?`BEST ${q.bestScore}/${q.count} · ${q.bestPercent}%`:'NOT STARTED'}</span><div class="subject-meta"><span>${q.attempted?'Retry Quiz':'Start Quiz'}</span><span>→</span></div></article>`).join('')}</div></section>`).join('');ui.loading(false)},
  async start(topic,number){ui.title('QUIZ','Preparing your questions');const result=await api.startQuiz(topic,number);state.quizRun=result.run;state.question=result.run.question;state.selected=null;state.started=Date.now();quizSets.renderQuestion()},
  renderQuestion(){const q=state.question,run=state.quizRun;ui.title('QUIZ',run.name);$('#screen').innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><span>${esc(run.name.toUpperCase())}</span><span>QUESTION ${q.number} / ${q.total}</span></div><div class="bar"><i style="width:${Math.round((q.number-1)/q.total*100)}%"></i></div><section class="card question-card"><div class="chips"><span class="chip">${esc(q.topic)}</span><span class="chip">${esc(q.difficulty)}</span></div><h1>${esc(q.text)}</h1><div class="options">${Object.entries(q.options).map(([key,value])=>`<button class="option" data-quiz-option="${key}"><b>${key}</b><span>${esc(value)}</span></button>`).join('')}</div><div class="quiz-actions"><button id="quizSubmit" class="primary" disabled>${q.number===q.total?'FINISH QUIZ':'SUBMIT & NEXT'} →</button></div></section></div>`;ui.loading(false)},
  select(key){state.selected=key;document.querySelectorAll('.option').forEach(el=>el.classList.toggle('selected',el.dataset.quizOption===key));$('#quizSubmit').disabled=false},
  async submit(){if(!state.selected)return;const button=$('#quizSubmit');button.disabled=true;button.textContent='SAVING…';const result=await ui.run(()=>api.submitQuizAnswer(state.quizRun.id,state.question.id,state.selected,Math.round((Date.now()-state.started)/1000)));if(!result){button.disabled=false;return}if(result.complete){state.lastResult=result.result;state.data=null;state.catalog=null;quizSets.result(result.result);ui.badges(result.badges);return}state.question=result.question;state.selected=null;state.started=Date.now();quizSets.renderQuestion()},
  result(result){ui.title('QUIZ COMPLETE',result.name);$('#screen').innerHTML=`<section class="card result-hero"><p class="eyebrow">${esc(result.name.toUpperCase())} COMPLETE</p><div class="result-score">${result.score}<small> / ${result.total}</small></div><h2>${result.percent}%</h2><div class="stats">${student.stat('✓',result.correct,'Correct')}${student.stat('×',result.wrong,'Wrong')}${student.stat('◎',result.percent+'%','Score')}${student.stat('⚡','+'+result.xpEarned,'XP earned')}</div><div class="result-actions"><button class="secondary" data-review="true">REVIEW ANSWERS</button><button class="secondary" data-retry-topic="${esc(result.topic)}" data-retry-number="${result.quizNumber}">RETRY QUIZ</button><button class="primary" data-action="quizzes">BACK TO QUIZZES</button></div></section>`;ui.loading(false)},
  review(){const result=state.lastResult;if(!result)return;ui.title('ANSWER REVIEW',result.name);$('#screen').innerHTML=`<button class="link-btn" data-result="true">← Back to result</button><div class="review-list">${result.review.map(item=>`<article class="card review-item"><h4>${item.number}. ${esc(item.question)}</h4><p class="${item.correct?'correct-text':'wrong-text'}">Your answer: ${esc(item.selectedAnswer)}. ${esc(item.selectedText)}</p><p class="correct-text">Correct answer: ${esc(item.correctAnswer)}. ${esc(item.correctText)}</p><p>${esc(item.explanation)}</p></article>`).join('')}</div>`;ui.loading(false)}
};

const coding={
  async home(){clearTimeout(state.autosaveTimer);state.assignment=null;state.assignmentDirty=false;ui.title('CODING ASSIGNMENTS','Build, practice and learn by creating real projects.');const result=await api.studentAssignments(),groups={};result.data.forEach(a=>{if(!groups[a.topic])groups[a.topic]=[];groups[a.topic].push(a)});$('#screen').innerHTML=Object.entries(groups).map(([topic,items])=>`<section class="quiz-section"><h3 class="quiz-section-title">${esc(topic)}</h3><div class="catalog-grid">${items.map(a=>`<article class="card assignment-card" data-assignment="${esc(a.id)}"><div class="subject-icon">&lt;/&gt;</div><h3>${esc(a.title)}</h3><p>${esc(a.shortDescription)}</p><div class="chips"><span class="chip">${esc(a.difficulty)}</span><span class="chip">${a.xp} XP</span></div><span class="assignment-status status-${String(a.submissionStatus).toLowerCase().replace(/\s/g,'-')}">${esc(a.submissionStatus)}${a.submissionStatus==='Completed'?' ✓':''}</span>${a.teacherRemarks&&a.submissionStatus==='Needs Revision'?`<p class="teacher-note">Teacher: ${esc(a.teacherRemarks)}</p>`:''}<div class="subject-meta"><span>${a.submissionStatus==='Not Started'?'Start Assignment':a.submissionStatus==='In Progress'||a.submissionStatus==='Needs Revision'?'Continue Assignment':'View Submission'}</span><span>→</span></div></article>`).join('')}</div></section>`).join('')||'<div class="card empty"><h2>No active assignments yet</h2></div>';ui.loading(false)},
  async open(id){ui.loading();const result=await api.openAssignment(id);state.assignment=result.data;state.assignmentDirty=false;coding.renderLab()},
  renderLab(){const {assignment:a,submission:s}=state.assignment,readOnly=s.readOnly;ui.title('CODING LAB',a.title);$('#screen').innerHTML=`<div class="coding-lab"><section class="lab-work"><button class="link-btn" data-action="coding">← All assignments</button><div class="card assignment-brief"><div class="card-head"><div><p class="eyebrow">${esc(a.topic)} · ${esc(a.difficulty)}</p><h3>${esc(a.title)}</h3></div><span class="chip">${a.xp} XP</span></div><p>${esc(a.instructions)}</p><ul>${a.requirements.map(r=>`<li data-requirement="${esc(r)}">○ ${esc(r)}</li>`).join('')}</ul>${s.teacherRemarks?`<div class="teacher-note"><b>Teacher Feedback</b><br>${esc(s.teacherRemarks)}</div>`:''}</div><div class="editor-block"><div class="editor-head"><b>Your HTML</b><span id="saveState">${readOnly?'View only':'Saved ✓'}</span></div><textarea id="htmlEditor" class="code-editor" spellcheck="false" ${readOnly?'readonly':''}>${esc(s.htmlCode)}</textarea></div><div class="editor-block"><div class="editor-head"><b>Your CSS</b></div><textarea id="cssEditor" class="code-editor" spellcheck="false" ${readOnly?'readonly':''}>${esc(s.cssCode)}</textarea></div><div class="lab-actions"><button class="secondary" data-run-code>RUN CODE</button>${!readOnly?'<button class="secondary" data-save-code>SAVE PROGRESS</button><button class="primary" data-submit-code>SUBMIT ASSIGNMENT</button>':''}</div>${s.status==='Submitted'?'<div class="success-note">Assignment Submitted ✓<br><small>Your assignment has been sent for review.</small></div>':''}${s.status==='Completed'?`<div class="success-note">Completed ✓ · +${s.xpAwarded} XP</div>`:''}</section><section class="preview-panel"><div class="editor-head"><b>LIVE PREVIEW</b><button class="link-btn" data-run-code>Refresh</button></div><iframe id="codePreview" sandbox="" title="Student code preview"></iframe><p id="previewEmpty">Click Run Code to see your page.</p></section></div>`;ui.loading(false);coding.guidance()},
  values(){return {html:$('#htmlEditor')?.value||'',css:$('#cssEditor')?.value||''}},
  changed(){if(!state.assignment||state.assignment.submission.readOnly)return;state.assignmentDirty=true;$('#saveState').textContent='Unsaved changes';clearTimeout(state.autosaveTimer);state.autosaveTimer=setTimeout(()=>coding.save(),7000);coding.guidance()},
  guidance(){const editor=$('#htmlEditor');if(!editor)return;const html=editor.value.toLowerCase();document.querySelectorAll('[data-requirement]').forEach(li=>{const r=li.dataset.requirement.toLowerCase();let ok=r.includes('heading')?/<h[1-6][\s>]/.test(html):r.includes('button')?/<button[\s>]/.test(html):r.includes('image')?/<img[\s>]/.test(html):r.includes('paragraph')?/<p[\s>]/.test(html):r.includes('list')?/<(ul|ol)[\s>]/.test(html):false;li.textContent=(ok?'✓ ':'○ ')+li.dataset.requirement;li.classList.toggle('requirement-done',ok)})},
  run(){const v=coding.values(),frame=$('#codePreview');frame.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https: data:; style-src 'unsafe-inline'; font-src https: data:"><style>${v.css}</style></head><body>${v.html}</body></html>`;$('#previewEmpty').classList.add('hidden')},
  async save(silent=false){if(!state.assignment||!state.assignmentDirty)return;const status=$('#saveState');if(status)status.textContent='Saving…';const v=coding.values(),result=await ui.run(()=>api.saveAssignment(state.assignment.assignment.id,v.html,v.css));if(!result)return;state.assignmentDirty=false;state.assignment.submission.htmlCode=v.html;state.assignment.submission.cssCode=v.css;if(status)status.textContent='Saved ✓';if(!silent)ui.toast('Your progress is saved ✓')},
  async submit(){if(!state.assignment||!confirm('Submit this assignment for teacher review?'))return;clearTimeout(state.autosaveTimer);const v=coding.values(),result=await ui.run(()=>api.submitAssignment(state.assignment.assignment.id,v.html,v.css));if(!result)return;state.assignmentDirty=false;state.data=null;ui.toast('Assignment submitted ✓');await coding.open(state.assignment.assignment.id)}
};

const admin={
  async home(){ui.title('ADMIN CONSOLE','Learning overview');const result=await api.adminDashboard(),data=result.data;$('#profileClass').textContent='Administrator';$('#screen').innerHTML=`<div class="admin-cards">${student.stat('◉',data.totals.students,'Total students')}${student.stat('●',data.totals.activeStudents,'Active students')}${student.stat('◇',data.totals.questions,'Active questions')}${student.stat('↗',data.totals.attempts,'Total attempts')}</div><section class="card table-card"><div class="card-head"><div><h3>Student overview</h3><small>Open a learner to review detailed performance</small></div><button class="primary" data-admin-coding>CODING ASSIGNMENTS</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>STUDENT</th><th>XP</th><th>LEVEL</th><th>COMPLETED</th><th>ACCURACY</th><th>STREAK</th><th>LAST ACTIVE</th></tr></thead><tbody>${data.students.map(item=>`<tr data-student="${esc(item.id)}"><td><b>${esc(item.name)}</b><br><small>${esc(item.className)}</small></td><td>${item.xp}</td><td>${item.level}</td><td>${item.completed}/${item.total}</td><td>${item.accuracy}%</td><td>${item.streak} days</td><td>${fmtDate(item.lastActive)}</td></tr>`).join('')}</tbody></table></div></section><div class="forms">${admin.xpForm(data.students)}${admin.questionForm()}</div>`;ui.loading(false)},
  xpForm(students){return `<section class="card"><div class="card-head"><div><h3>Award XP</h3><small>Record an offline or bonus activity</small></div></div><form id="xpForm"><label>Student<select name="studentId">${students.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label><div class="form-grid"><label>Activity<select name="activityType"><option>Offline Class Task</option><option>Assignment</option><option>Project</option><option>Bonus</option><option>Other</option></select></label><label>XP<input name="amount" type="number" min="1" max="10000" value="50" required></label><label class="full">Description<input name="description" maxlength="200" required placeholder="What did the student achieve?"></label></div><button class="primary" type="submit" style="margin-top:18px">AWARD XP</button></form></section>`},
  questionForm(){return `<section class="card"><div class="card-head"><div><h3>Add question</h3><small>Google Sheets remains the primary bulk editor</small></div></div><form id="questionForm"><div class="form-grid"><label>Topic<input name="topic" required maxlength="80"></label><label>Subtopic<input name="subTopic" maxlength="80"></label><label>Difficulty<select name="difficulty"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>XP<input name="xp" type="number" value="10" min="1" max="100"></label><label class="full">Question<textarea name="question" required maxlength="1000"></textarea></label>${['A','B','C','D'].map(letter=>`<label>Option ${letter}<input name="option${letter}" required maxlength="500"></label>`).join('')}<label>Correct answer<select name="correctAnswer"><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label class="full">Explanation<textarea name="explanation" required maxlength="1000"></textarea></label></div><button class="primary" type="submit">ADD QUESTION</button></form></section>`},
  async award(form){const data=Object.fromEntries(new FormData(form)),result=await ui.run(()=>api.awardManualXp(data));if(!result)return;ui.toast(`XP awarded. New total: ${result.xp}`);ui.badges(result.badges);form.reset()},
  async addQuestion(form){const result=await ui.run(()=>api.addQuestion(Object.fromEntries(new FormData(form))));if(!result)return;ui.toast(`Question ${result.id} added`);form.reset()},
  async coding(){ui.loading();const result=await api.adminAssignments();state.adminCoding=result.data;ui.title('ADMIN · CODING','Assignments and submissions');const d=result.data;$('#screen').innerHTML=`<button class="link-btn" data-action="admin">← Admin overview</button><div class="forms"><section class="card"><div class="card-head"><div><h3>Assignment editor</h3><small>Create or select an assignment to edit</small></div></div><label>Select existing<select id="assignmentPicker"><option value="">New assignment</option>${d.assignments.map(a=>`<option value="${esc(a.id)}">${esc(a.id)} · ${esc(a.title)}</option>`).join('')}</select></label><form id="assignmentForm"><div class="form-grid"><label>ID<input name="id" required></label><label>Title<input name="title" required></label><label>Topic<input name="topic" required placeholder="HTML & CSS"></label><label>Difficulty<select name="difficulty"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label class="full">Short description<input name="shortDescription" required></label><label class="full">Instructions<textarea name="instructions" required></textarea></label><label class="full">Requirements<textarea name="requirements" placeholder="Heading|Paragraph|Button"></textarea></label><label class="full">Starter HTML<textarea name="starterHTML" class="code-editor"></textarea></label><label class="full">Starter CSS<textarea name="starterCSS" class="code-editor"></textarea></label><label>XP<input name="xp" type="number" min="1" value="50"></label><label>Order<input name="order" type="number" min="0" value="1"></label><label>Status<select name="status"><option>Active</option><option>Inactive</option></select></label></div><button class="primary" type="submit">SAVE ASSIGNMENT</button></form></section><section class="card"><div class="card-head"><div><h3>Student submissions</h3><small>${d.submissions.length} total</small></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>STUDENT</th><th>ASSIGNMENT</th><th>TOPIC</th><th>STATUS</th><th>DATE</th></tr></thead><tbody>${d.submissions.map(s=>`<tr data-submission="${esc(s.id)}"><td>${esc(s.studentName)}</td><td>${esc(s.assignmentTitle)}</td><td>${esc(s.topic)}</td><td>${esc(s.status)}</td><td>${fmtDate(s.submittedAt||s.lastSavedAt)}</td></tr>`).join('')}</tbody></table></div></section></div>`;ui.loading(false)},
  fillAssignment(id){const form=$('#assignmentForm'),a=state.adminCoding.assignments.find(x=>x.id===id);form.reset();if(!a)return;Object.entries({id:a.id,title:a.title,topic:a.topic,difficulty:a.difficulty,shortDescription:a.shortDescription,instructions:a.instructions,requirements:a.requirements.join('|'),starterHTML:a.starterHTML,starterCSS:a.starterCSS,xp:a.xp,order:a.order,status:a.status}).forEach(([k,v])=>{if(form.elements[k])form.elements[k].value=v})},
  async saveCoding(form){const result=await ui.run(()=>api.adminSaveAssignment(Object.fromEntries(new FormData(form))));if(!result)return;ui.toast(`Assignment ${result.id} saved`);await admin.coding()},
  async review(id){ui.loading();const result=await api.adminSubmission(id);state.review=result.data;const d=result.data;ui.title('ASSIGNMENT REVIEW',d.assignment.title);$('#screen').innerHTML=`<button class="link-btn" data-admin-coding>← All submissions</button><div class="coding-lab"><section class="lab-work"><div class="card"><p class="eyebrow">${esc(d.student.name)} · ${fmtDate(d.submission.submittedAt)}</p><h3>${esc(d.assignment.title)}</h3><ul>${d.assignment.requirements.map(r=>`<li>${esc(r)}</li>`).join('')}</ul></div><div class="editor-block"><div class="editor-head"><b>Student HTML</b></div><textarea id="reviewHtml" class="code-editor" readonly>${esc(d.submission.htmlCode)}</textarea></div><div class="editor-block"><div class="editor-head"><b>Student CSS</b></div><textarea id="reviewCss" class="code-editor" readonly>${esc(d.submission.cssCode)}</textarea></div><label>Teacher Remarks<textarea id="reviewRemarks">${esc(d.submission.remarks)}</textarea></label><div class="lab-actions"><button class="secondary" data-review-decision="revision">NEEDS REVISION</button><button class="primary" data-review-decision="approve">APPROVE & AWARD ${d.assignment.xp} XP</button></div></section><section class="preview-panel"><div class="editor-head"><b>LIVE PREVIEW</b></div><iframe id="reviewPreview" sandbox="" title="Submission preview"></iframe></section></div>`;$('#reviewPreview').srcdoc=`<!doctype html><html><head><meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src https: data:; style-src 'unsafe-inline'; font-src https: data:"><style>${d.submission.cssCode}</style></head><body>${d.submission.htmlCode}</body></html>`;ui.loading(false)},
  async decide(decision){const remarks=$('#reviewRemarks').value;if(decision==='revision'&&!remarks.trim()){ui.toast('Add teacher remarks before requesting revision.','error');return}if(decision==='approve'&&!confirm('Approve this work and award XP?'))return;const result=await ui.run(()=>api.adminReviewAssignment(state.review.submission.id,decision,remarks));if(!result)return;ui.toast(result.duplicate?'XP was already awarded.':decision==='approve'?`Approved · +${result.xpAwarded} XP`:'Returned for revision');await admin.coding()},
  async detail(id){ui.loading();const result=await ui.run(()=>api.studentDetail(id));if(!result)return;const data=result.data,stats=data.stats;ui.title('STUDENT DETAIL',data.profile.name);$('#screen').innerHTML=`<button class="link-btn" data-action="admin">← Back to all students</button><div class="stats">${student.stat('⚡',stats.xp,'Total XP')}${student.stat('◇',stats.completed,'Completed')}${student.stat('◎',stats.accuracy+'%','Accuracy')}${student.stat('🔥',stats.streak+' days','Current streak')}</div><div class="grid2"><section class="card"><div class="card-head"><h3>Topic performance</h3></div>${student.topics(data.topics)}</section><section class="card"><div class="card-head"><h3>Earned badges</h3></div><div class="badge-row">${student.badgeHtml(data.badges.filter(x=>x.earned))}</div></section></div><section class="card table-card"><div class="card-head"><h3>Recent attempts</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>DATE</th><th>QUESTION</th><th>TOPIC</th><th>ANSWER</th><th>RESULT</th><th>XP</th></tr></thead><tbody>${data.attempts.map(item=>`<tr><td>${fmtDate(item.Timestamp)}</td><td>${esc(item.QuestionID)}</td><td>${esc(item.Topic)}</td><td>${esc(item.SelectedAnswer)}</td><td>${String(item.IsCorrect).toLowerCase()==='true'?'Correct':'Wrong'}</td><td>${item.XPEarned}</td></tr>`).join('')}</tbody></table></div></section>`;ui.loading(false)}
};

const renderAdminCoding=admin.coding.bind(admin);
admin.coding=async()=>{await renderAdminCoding();const table=$('[data-submission]')?.closest('.table-wrap');if(table)table.insertAdjacentHTML('beforebegin','<label style="margin:0 0 14px">Filter submissions<input id="submissionFilter" placeholder="Student, assignment, topic or status"></label>')};
const renderStudentHome=student.home.bind(student);
student.home=async()=>{await renderStudentHome();const a=state.data?.assignments;if(!a)return;$('#screen').insertAdjacentHTML('beforeend',`<section class="card table-card"><div class="card-head"><div><h3>Coding Progress</h3><small>${a.recent?`${esc(a.recent.title)} · ${esc(a.recent.status)}`:'Start your first real project'}</small></div><button class="primary" data-action="coding">OPEN CODING LAB →</button></div><div class="subject-meta"><span>Completed: ${a.completed}</span><span>In Progress: ${a.inProgress}</span><span>Submitted: ${a.submitted}</span></div></section>`)};

$('#loginForm').addEventListener('submit',auth.login);$('#logoutBtn').addEventListener('click',auth.logout);$('#modalClose').addEventListener('click',ui.closeModal);
$('#nav').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(button)router.go(button.dataset.view)});
$('#screen').addEventListener('click',event=>{
  const action=event.target.closest('[data-action]')?.dataset.action;if(action)router.go(action);
  const topic=event.target.closest('[data-practice-topic]');if(topic)ui.run(()=>practice.load(topic.dataset.practiceTopic));
  const practiceOption=event.target.closest('[data-option]');if(practiceOption)practice.select(practiceOption.dataset.option);
  if(event.target.id==='practiceSubmit'){if(event.target.dataset.next)ui.run(()=>practice.load());else practice.submit()}
  const quizCard=event.target.closest('[data-quiz-topic]');if(quizCard)ui.run(()=>quizSets.start(quizCard.dataset.quizTopic,Number(quizCard.dataset.quizNumber)));
  const quizOption=event.target.closest('[data-quiz-option]');if(quizOption)quizSets.select(quizOption.dataset.quizOption);
  if(event.target.id==='quizSubmit')quizSets.submit();
  const retry=event.target.closest('[data-retry-topic]');if(retry)ui.run(()=>quizSets.start(retry.dataset.retryTopic,Number(retry.dataset.retryNumber)));
  if(event.target.closest('[data-review]'))quizSets.review();if(event.target.closest('[data-result]'))quizSets.result(state.lastResult);
  const row=event.target.closest('[data-student]');if(row)admin.detail(row.dataset.student);
  const assignment=event.target.closest('[data-assignment]');if(assignment)ui.run(()=>coding.open(assignment.dataset.assignment));
  if(event.target.closest('[data-run-code]'))coding.run();if(event.target.closest('[data-save-code]'))coding.save();if(event.target.closest('[data-submit-code]'))coding.submit();
  if(event.target.closest('[data-admin-coding]'))ui.run(()=>admin.coding());const submission=event.target.closest('[data-submission]');if(submission)ui.run(()=>admin.review(submission.dataset.submission));
  const decision=event.target.closest('[data-review-decision]');if(decision)admin.decide(decision.dataset.reviewDecision);
});
$('#screen').addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='xpForm')admin.award(event.target);if(event.target.id==='questionForm')admin.addQuestion(event.target);if(event.target.id==='assignmentForm')admin.saveCoding(event.target)});
$('#screen').addEventListener('input',event=>{if(event.target.id==='htmlEditor'||event.target.id==='cssEditor')coding.changed()});
$('#screen').addEventListener('input',event=>{if(event.target.id==='submissionFilter'){const query=event.target.value.toLowerCase();document.querySelectorAll('[data-submission]').forEach(row=>row.classList.toggle('hidden',!row.textContent.toLowerCase().includes(query)))}});
$('#screen').addEventListener('change',event=>{if(event.target.id==='assignmentPicker')admin.fillAssignment(event.target.value)});

if(state.user){auth.showApp();router.go(state.user.role==='ADMIN'?'admin':'dashboard')}
