import './styles.css';
import {api,session,ApiError} from './api.js';

const state={user:session.get(),data:null,question:null,selected:null,started:0};
const $=selector=>document.querySelector(selector);
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
const fmtDate=value=>value?new Date(value).toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric'}):'—';

const ui={
  toast(message,type='info'){const el=$('#toast');el.textContent=message;el.className=`toast show ${type}`;clearTimeout(ui.toastTimer);ui.toastTimer=setTimeout(()=>el.className='toast',3200)},
  loading(show=true){$('#loading').classList.toggle('hidden',!show);if(show)$('#screen').innerHTML=''},
  title(kicker,title){$('#headerKicker').textContent=kicker;$('#pageTitle').textContent=title},
  badges(items){if(!items?.length)return;const badge=items[0];$('#modalIcon').textContent=badge.icon||'🏆';$('#modalTitle').textContent=badge.name;$('#modalText').textContent=badge.description;$('#modal').classList.remove('hidden')},
  closeModal(){$('#modal').classList.add('hidden')},
  async run(work){try{return await work()}catch(error){if(error instanceof ApiError&&error.code==='SESSION_EXPIRED'){auth.clear('Your session expired. Please sign in again.');return null}ui.toast(error.message||'Something went wrong.','error');return null}}
};

const auth={
  async login(event){event.preventDefault();const button=$('#loginButton');$('#loginError').textContent='';button.disabled=true;button.querySelector('span').textContent='SIGNING IN…';try{const result=await api.login($('#loginId').value.trim(),$('#loginPin').value);state.user={token:result.token,role:result.role,name:result.name};session.set(state.user);auth.showApp();await router.go(result.role==='ADMIN'?'admin':'dashboard')}catch(error){$('#loginError').textContent=error.message||'Unable to sign in.'}finally{button.disabled=false;button.querySelector('span').textContent='ENTER LEARNING SPACE'}},
  showApp(){const user=state.user;$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#profileName').textContent=user?.name||'Learner';$('#avatar').textContent=(user?.name||'L')[0].toUpperCase();$('#profileClass').textContent=user?.role==='ADMIN'?'Administrator':'Class 8';document.querySelectorAll('.admin-only').forEach(el=>el.classList.toggle('hidden',user?.role!=='ADMIN'));document.querySelectorAll('#nav button:not(.admin-only)').forEach(el=>el.classList.toggle('hidden',user?.role==='ADMIN'&&el.dataset.view!=='dashboard'))},
  async logout(){try{await api.logout()}catch(_){}auth.clear()},
  clear(message=''){session.clear();state.user=null;state.data=null;$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden');$('#loginPin').value='';if(message)$('#loginError').textContent=message}
};

const router={
  async go(view){if(state.user?.role==='ADMIN')view='admin';document.querySelectorAll('#nav button').forEach(el=>el.classList.toggle('active',el.dataset.view===view));ui.loading();const page=view==='quiz'?quiz.load:view==='badges'?student.badges:view==='progress'?student.progress:view==='admin'?admin.home:student.home;const result=await ui.run(()=>page());if(result===null)ui.loading(false)}
};

const student={
  async fetch(){const result=await api.studentDashboard();state.data=result.data;const data=result.data;$('#profileName').textContent=data.profile.name;$('#profileClass').textContent=data.profile.className;$('#avatar').textContent=data.profile.name[0];return data},
  stat(icon,value,label){return `<article class="card stat"><span class="icon">${icon}</span><strong>${value}</strong><small>${label}</small></article>`},
  badgeHtml(badges){return badges.map(b=>`<div class="badge ${b.earned?'':'locked'}" title="${esc(b.description)}"><div class="medal">${esc(b.icon||'✦')}</div><small>${esc(b.name)}</small></div>`).join('')||'<p class="muted">No badges available yet.</p>'},
  activity(items){return `<div class="activity">${items.map(item=>`<div class="activity-item"><span class="dot">+</span><p>${esc(item.title)}<small>${esc(item.type)} · ${fmtDate(item.date)}</small></p><b>${item.xp>=0?'+':''}${item.xp} XP</b></div>`).join('')||'<p class="muted">Your learning activity will appear here.</p>'}</div>`},
  topics(items){return items.map(item=>`<div class="topic"><div><b>${esc(item.topic)}</b><span>${item.accuracy}% · ${item.attempted} attempts</span></div><div class="bar"><i style="width:${item.accuracy}%"></i></div></div>`).join('')||'<p class="muted">Complete a quiz to unlock topic insights.</p>'},
  async home(){ui.title('STUDENT DASHBOARD','Your learning space');const data=await student.fetch(),stats=data.stats,next=data.nextQuestion;$('#screen').innerHTML=`<div class="hero"><section class="hero-main"><p class="eyebrow">WELCOME BACK</p><h1>Hey, ${esc(data.profile.name.split(' ')[0])}!<br><span class="gradient">Keep the momentum.</span></h1><p>${next?`Your next challenge is ready in ${esc(next.topic)}. Complete it to keep your progress moving.`:'You completed every active question. Brilliant work!'}</p>${next?'<button class="primary continue" data-action="quiz">CONTINUE QUIZ &nbsp; →</button>':''}</section><section class="card level-card"><div class="level-top"><div class="level-number"><small>CURRENT LEVEL</small>${data.profile.level}</div><span class="level-orb">✦</span></div><div class="bar"><i style="width:${data.level.percent}%"></i></div><div class="barline"><span>${stats.xp} XP</span><span>${data.level.nextAt?data.level.nextAt+' XP':'MAX LEVEL'}</span></div><p>${data.level.nextAt?`<b>${data.level.toNext} XP</b> to reach Level ${data.profile.level+1}`:'You reached the highest level.'}</p></section></div><div class="stats">${student.stat('⚡',stats.xp,'Total XP')}${student.stat('◇',stats.completed+' / '+stats.totalQuestions,'Questions completed')}${student.stat('◎',stats.accuracy+'%','Overall accuracy')}${student.stat('🔥',stats.streak+' days','Current streak')}</div><div class="grid2"><section class="card"><div class="card-head"><div><h3>My badges</h3><small>${data.badges.filter(x=>x.earned).length} achievements unlocked</small></div><button class="link-btn" data-action="badges">View all →</button></div><div class="badge-row">${student.badgeHtml(data.badges.slice(0,6))}</div></section><section class="card"><div class="card-head"><h3>Recent activity</h3></div>${student.activity(data.recent.slice(0,4))}</section></div><div class="grid2"><section class="card"><div class="card-head"><div><h3>Topic performance</h3><small>Accuracy across your learning areas</small></div><button class="link-btn" data-action="progress">Details →</button></div>${student.topics(data.topics.slice(0,4))}</section><section class="card"><div class="card-head"><h3>Today’s focus</h3></div><p class="muted">${next?'Complete your next challenge and protect your learning streak.':'Review your badges and celebrate your progress.'}</p><div class="bar green"><i style="width:${next?'62':'100'}%"></i></div><div class="barline"><span>${next?esc(next.topic):'Course complete'}</span><span>${next?esc(next.difficulty):'100%'}</span></div></section></div>`;ui.loading(false)},
  async badges(){ui.title('ACHIEVEMENTS','Your badge collection');const data=await student.fetch(),earned=data.badges.filter(x=>x.earned).length;$('#screen').innerHTML=`<section class="card"><div class="card-head"><div><h3>${earned} of ${data.badges.length} unlocked</h3><small>Every milestone marks real progress.</small></div></div><div class="badge-row">${student.badgeHtml(data.badges)}</div></section>`;ui.loading(false)},
  async progress(){ui.title('PERFORMANCE','Progress & insights');const data=await student.fetch(),stats=data.stats;$('#screen').innerHTML=`<div class="stats">${student.stat('◎',stats.accuracy+'%','Overall accuracy')}${student.stat('◇',stats.attempted,'Total attempts')}${student.stat('✓',stats.correct,'Correct answers')}${student.stat('×',stats.wrong,'Incorrect answers')}</div><div class="grid2"><section class="card"><div class="card-head"><div><h3>Topic performance</h3><small>Spot strengths and areas to revisit</small></div></div>${student.topics(data.topics)}</section><section class="card"><div class="card-head"><h3>Learning streak</h3></div><div class="level-number"><small>LONGEST STREAK</small>${stats.longestStreak} <span style="font-size:18px">days 🔥</span></div><p class="muted">Current streak: ${stats.streak} days</p></section></div>`;ui.loading(false)}
};

const quiz={
  async load(){ui.title('CONTINUE QUIZ','One question at a time');state.selected=null;state.started=Date.now();const result=await api.nextQuestion();state.question=result.question;quiz.render()},
  render(){const q=state.question;if(!q){$('#screen').innerHTML='<div class="card empty"><div class="big">🏆</div><h2>You’re all caught up!</h2><p>There are no incomplete active questions.</p><button class="primary" data-action="dashboard">BACK TO DASHBOARD</button></div>';ui.loading(false);return}$('#screen').innerHTML=`<div class="quiz-wrap"><div class="quiz-top"><span>QUESTION ${q.number} OF ${q.total}</span><span>${q.xp} XP AVAILABLE</span></div><div class="bar"><i style="width:${Math.round((q.number-1)/q.total*100)}%"></i></div><section class="card question-card"><div class="chips"><span class="chip">${esc(q.topic)}</span><span class="chip">${esc(q.difficulty)}</span>${q.subTopic?`<span class="chip">${esc(q.subTopic)}</span>`:''}</div><h1>${esc(q.text)}</h1><div class="options">${Object.entries(q.options).map(([key,value])=>`<button class="option" data-option="${key}"><b>${key}</b><span>${esc(value)}</span></button>`).join('')}</div><div id="feedback"></div><div class="quiz-actions"><button id="submitBtn" class="primary" disabled>SUBMIT ANSWER</button></div></section></div>`;ui.loading(false)},
  select(key){if($('#feedback')?.innerHTML)return;state.selected=key;document.querySelectorAll('.option').forEach(el=>el.classList.toggle('selected',el.dataset.option===key));$('#submitBtn').disabled=false},
  async submit(){if(!state.selected)return;const button=$('#submitBtn');button.disabled=true;button.textContent='CHECKING…';const result=await ui.run(()=>api.submitAnswer(state.question.id,state.selected,Math.round((Date.now()-state.started)/1000)));if(!result){button.disabled=false;button.textContent='SUBMIT ANSWER';return}document.querySelectorAll('.option').forEach(el=>{el.disabled=true;if(el.dataset.option===result.correctAnswer)el.classList.add('correct');if(el.dataset.option===state.selected&&!result.correct)el.classList.add('wrong')});$('#feedback').className=`feedback${result.correct?'':' wrong'}`;$('#feedback').innerHTML=`<h3>${result.correct?`Correct! ${result.xpEarned?`+${result.xpEarned} XP`:''}`:'Not quite.'}</h3><p>${esc(result.explanation)}</p>${!result.correct?`<small>Correct answer: ${esc(result.correctAnswer)}. ${esc(result.correctText||'')}</small>`:''}`;button.textContent='NEXT QUESTION →';button.disabled=false;button.dataset.next='true';ui.badges(result.badges)}
};

const admin={
  async home(){ui.title('ADMIN CONSOLE','Learning overview');const result=await api.adminDashboard(),data=result.data;$('#profileClass').textContent='Administrator';$('#screen').innerHTML=`<div class="admin-cards">${student.stat('◉',data.totals.students,'Total students')}${student.stat('●',data.totals.activeStudents,'Active students')}${student.stat('◇',data.totals.questions,'Active questions')}${student.stat('↗',data.totals.attempts,'Total attempts')}</div><section class="card table-card"><div class="card-head"><div><h3>Student overview</h3><small>Open a learner to review detailed performance</small></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>STUDENT</th><th>XP</th><th>LEVEL</th><th>COMPLETED</th><th>ACCURACY</th><th>STREAK</th><th>LAST ACTIVE</th></tr></thead><tbody>${data.students.map(item=>`<tr data-student="${esc(item.id)}"><td><b>${esc(item.name)}</b><br><small>${esc(item.className)}</small></td><td>${item.xp}</td><td>${item.level}</td><td>${item.completed}/${item.total}</td><td>${item.accuracy}%</td><td>${item.streak} days</td><td>${fmtDate(item.lastActive)}</td></tr>`).join('')}</tbody></table></div></section><div class="forms">${admin.xpForm(data.students)}${admin.questionForm()}</div>`;ui.loading(false)},
  xpForm(students){return `<section class="card"><div class="card-head"><div><h3>Award XP</h3><small>Record an offline or bonus activity</small></div></div><form id="xpForm"><label>Student<select name="studentId">${students.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select></label><div class="form-grid"><label>Activity<select name="activityType"><option>Offline Class Task</option><option>Assignment</option><option>Project</option><option>Bonus</option><option>Other</option></select></label><label>XP<input name="amount" type="number" min="1" max="10000" value="50" required></label><label class="full">Description<input name="description" maxlength="200" required placeholder="What did the student achieve?"></label></div><button class="primary" type="submit" style="margin-top:18px">AWARD XP</button></form></section>`},
  questionForm(){return `<section class="card"><div class="card-head"><div><h3>Add question</h3><small>Google Sheets remains the primary bulk editor</small></div></div><form id="questionForm"><div class="form-grid"><label>Topic<input name="topic" required maxlength="80"></label><label>Subtopic<input name="subTopic" maxlength="80"></label><label>Difficulty<select name="difficulty"><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>XP<input name="xp" type="number" value="10" min="1" max="100"></label><label class="full">Question<textarea name="question" required maxlength="1000"></textarea></label>${['A','B','C','D'].map(letter=>`<label>Option ${letter}<input name="option${letter}" required maxlength="500"></label>`).join('')}<label>Correct answer<select name="correctAnswer"><option>A</option><option>B</option><option>C</option><option>D</option></select></label><label class="full">Explanation<textarea name="explanation" required maxlength="1000"></textarea></label></div><button class="primary" type="submit">ADD QUESTION</button></form></section>`},
  async award(form){const data=Object.fromEntries(new FormData(form)),result=await ui.run(()=>api.awardManualXp(data));if(!result)return;ui.toast(`XP awarded. New total: ${result.xp}`);ui.badges(result.badges);form.reset()},
  async addQuestion(form){const result=await ui.run(()=>api.addQuestion(Object.fromEntries(new FormData(form))));if(!result)return;ui.toast(`Question ${result.id} added`);form.reset()},
  async detail(id){ui.loading();const result=await ui.run(()=>api.studentDetail(id));if(!result)return;const data=result.data,stats=data.stats;ui.title('STUDENT DETAIL',data.profile.name);$('#screen').innerHTML=`<button class="link-btn" data-action="admin">← Back to all students</button><div class="stats">${student.stat('⚡',stats.xp,'Total XP')}${student.stat('◇',stats.completed,'Completed')}${student.stat('◎',stats.accuracy+'%','Accuracy')}${student.stat('🔥',stats.streak+' days','Current streak')}</div><div class="grid2"><section class="card"><div class="card-head"><h3>Topic performance</h3></div>${student.topics(data.topics)}</section><section class="card"><div class="card-head"><h3>Earned badges</h3></div><div class="badge-row">${student.badgeHtml(data.badges.filter(x=>x.earned))}</div></section></div><section class="card table-card"><div class="card-head"><h3>Recent attempts</h3></div><div class="table-wrap"><table class="data-table"><thead><tr><th>DATE</th><th>QUESTION</th><th>TOPIC</th><th>ANSWER</th><th>RESULT</th><th>XP</th></tr></thead><tbody>${data.attempts.map(item=>`<tr><td>${fmtDate(item.Timestamp)}</td><td>${esc(item.QuestionID)}</td><td>${esc(item.Topic)}</td><td>${esc(item.SelectedAnswer)}</td><td>${String(item.IsCorrect).toLowerCase()==='true'?'Correct':'Wrong'}</td><td>${item.XPEarned}</td></tr>`).join('')}</tbody></table></div></section>`;ui.loading(false)}
};

$('#loginForm').addEventListener('submit',auth.login);$('#logoutBtn').addEventListener('click',auth.logout);$('#modalClose').addEventListener('click',ui.closeModal);
$('#nav').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(button)router.go(button.dataset.view)});
$('#screen').addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action)router.go(action);const option=event.target.closest('[data-option]');if(option)quiz.select(option.dataset.option);const row=event.target.closest('[data-student]');if(row)admin.detail(row.dataset.student);if(event.target.id==='submitBtn'){if(event.target.dataset.next)quiz.load();else quiz.submit()}});
$('#screen').addEventListener('submit',event=>{event.preventDefault();if(event.target.id==='xpForm')admin.award(event.target);if(event.target.id==='questionForm')admin.addQuestion(event.target)});

if(state.user){auth.showApp();router.go(state.user.role==='ADMIN'?'admin':'dashboard')}
